# Generated by Django 5.1.3 on 2024-11-22 23:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.DecimalField(decimal_places=2, help_text='Ingreso mensual del usuario.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('requested_amount', models.DecimalField(decimal_places=2, help_text='Monto solicitado.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('monthly_interest_rate', models.DecimalField(decimal_places=4, help_text='Tasa de interés mensual (%).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0001')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('term_months', models.PositiveIntegerField(help_text='Plazo del financiamiento (meses).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(360)])),
                ('credit_history', models.BooleanField(default=False, help_text='¿Tiene historial crediticio positivo?')),
                ('score', models.IntegerField(default=0, help_text='Puntaje calculado automáticamente.', validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(850)])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última actualización del registro')),
                ('user', models.OneToOneField(help_text='Usuario asociado al puntaje crediticio.', on_delete=django.db.models.deletion.CASCADE, related_name='credit_score', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='creditScore_created_9ae822_idx'), models.Index(fields=['user'], name='creditScore_user_id_e42f98_idx'), models.Index(fields=['score'], name='creditScore_score_4c9e65_idx')],
            },
        ),
    ]
