# Generated by Django 5.1.3 on 2024-11-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditScore', '0001_initial'),
        ('financing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditscore',
            name='active_financings',
            field=models.ManyToManyField(blank=True, help_text='Financiamientos activos del usuario', related_name='credit_scores', to='financing.financing'),
        ),
    ]
