# Generated by Django 5.1.3 on 2024-12-05 21:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditScore', '0002_creditscore_active_financings'),
        ('financing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditscore',
            name='active_financings',
            field=models.ManyToManyField(blank=True, help_text='Lista de financiamientos activos asociados al usuario.', related_name='credit_scores', to='financing.financing'),
        ),
        migrations.AlterField(
            model_name='creditscore',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro.'),
        ),
        migrations.AlterField(
            model_name='creditscore',
            name='credit_history',
            field=models.BooleanField(default=False, help_text='Indica si el usuario tiene un historial crediticio positivo.'),
        ),
        migrations.AlterField(
            model_name='creditscore',
            name='monthly_interest_rate',
            field=models.DecimalField(decimal_places=4, help_text='Tasa de interés mensual expresada como porcentaje.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0001')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='creditscore',
            name='requested_amount',
            field=models.DecimalField(decimal_places=2, help_text='Monto solicitado por el usuario.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='creditscore',
            name='term_months',
            field=models.PositiveIntegerField(help_text='Plazo del financiamiento en meses.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(360)]),
        ),
        migrations.AlterField(
            model_name='creditscore',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Última actualización del registro.'),
        ),
        migrations.AlterField(
            model_name='creditscore',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Usuario asociado al puntaje crediticio.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_score', to=settings.AUTH_USER_MODEL),
        ),
    ]
