# Generated by Django 5.1.3 on 2024-12-06 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditScore', '0003_alter_creditscore_active_financings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditscore',
            name='monthly_interest_rate',
        ),
        migrations.RemoveField(
            model_name='creditscore',
            name='requested_amount',
        ),
        migrations.RemoveField(
            model_name='creditscore',
            name='term_months',
        ),
    ]
